### PR TITLE
Set more fields on the request

### LINKED ISSUE #1: set more fields in the request
### Environment

Provide at least:
* Ruby Version = 2.5
* Persistent HTTP Version = 2.0.3
* Semantic Logger Version = 4.6.1
* Secret Config Version = 0.7.0
* Opinionated HTTP Version = 0.0.3
* Application/framework names and versions Rails = 5.2.3
* Full Stack Trace, if an exception is being raised.

### Expected Behavior

* Describe your expectation of how Opinionated HTTP should behave.
Should be able to set the request body, headers, and basic_auth in #post
* Ideally, provide a standalone Ruby script or a link to an example repository that helps reproduce the issue.

### Actual Behavior

* Describe or show the actual behavior.
Currently only accepts a set of params to feed to #set_form_data
* Provide text or screen capture showing the behavior.

### Pull Request

* Consider submitting a Pull Request with a fix for the issue.
* Or, even a Pull request that only includes a test that reproduces the problem.

### PR DESCRIPTION
**Pull request by ADKebert**
### Issue 1 (if available)
closes #1

### Description of changes
extend Client#post to be able to set more fields in the request including headers, body, and authentication with basic_auth

create Client#generic_request for code reuse and testing purposes

check args to generic_request for collisions and raise ArgumentErrors rather than allow fields to be overwritten

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lib/opinionated_http/client.rb [hunk 1]
```diff
@@ -49,22 +49,33 @@ def get(action:, path: "/#{action}", parameters: nil)
...
-      request.set_form_data(parameters) if parameters
+      request = generic_request(path: path, verb: 'Post', headers: headers, body: body, form_data: form_data, auth: auth)
 
       response = request_with_retry(action: action, path: path, request: request)
 
       response.body
     end
 
+    # auth expects hash of the form {'username' =>, 'password' =>}
+    def generic_request(path:, verb:, headers: nil, body: nil, form_data: nil, auth: nil)
```
Comment (reidmorrison) [inline lib/opinionated_http/client.rb]: Instead of using `:auth`, could we supply `:username` and `:password` directly as arguments?

Comment (ADKebert) [reply lib/opinionated_http/client.rb]: certainly
